=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Schema/interaction.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema targetNamespace="http://opends.eu/drivingtask/interaction"
elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://opends.eu/drivingtask/interaction">

    <xs:element name="interaction">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="1" name="activities" type="activities"/>
                <xs:element minOccurs="0" maxOccurs="1" name="triggers" type="triggers"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="triggers">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="trigger" type="trigger"/>
        </xs:sequence>
    </xs:complexType>
   
    <xs:complexType name="trigger">
        <xs:sequence>
            <xs:element name="activities" type="activities"/>
            <xs:element name="condition" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="priority" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="activities">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="activity" type="activity"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="activity">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="action" type="action"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="ref" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="action">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="parameter" type="parameter"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="delay" type="xs:float"/>
        <xs:attribute name="repeat" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="parameter">
        <xs:attribute name="value" type="xs:string" use="required" />
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>

=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Projects/Village2/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">


	<activities>
		<activity id="activity01">
			<action id="requestGreenTrafficLight" delay="0" repeat="0">
				<parameter name="trafficLightID" value="TrafficLight_1" />
			</action>
		</activity>
		<activity id="activity02">
			<action id="requestGreenTrafficLight" delay="0" repeat="0">
				<parameter name="trafficLightID" value="TrafficLight_2" />
			</action>
		</activity>
		<activity id="activity03">
			<action id="requestGreenTrafficLight" delay="0" repeat="0">
				<parameter name="trafficLightID" value="TrafficLight_3" />
			</action>
		</activity>
		<activity id="message">
			<action id="sendMessage" delay="0" repeat="4">
				<parameter name="text" value="Test" />
				<parameter name="duration" value="1" />
			</action>
		</activity>
	</activities>
	
	<triggers>
		<trigger id="collideWithTrafficLightBox1" priority="1">
            <activities>
                <activity ref="activity01"/>
            </activities>
            
            <condition>collideWith:triggerBox1</condition>
        </trigger>
    
		<trigger id="collideWithTrafficLightBox2" priority="1">
            <activities>
                <activity ref="activity02"/>
            </activities>
            
            <condition>collideWith:triggerBox2</condition>
        </trigger>
        
        <trigger id="collideWithTrafficLightBox3" priority="1">
            <activities>
                <activity ref="activity03"/>
            </activities>
            
            <condition>collideWith:triggerBox3</condition>
        </trigger>
        
        <trigger id="pressAccelerator" priority="1">
            <activities>
                <activity ref="message"/>
            </activities>
            
            <condition>pressPedal:accelerator:0.56</condition>
        </trigger>
	</triggers>
	
</interaction>

=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Projects/ConTReTask/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">


	<activities>
		<activity id="resumeSim">
			<action id="resumeSimulation" delay="0" repeat="0">
			</action>
		</activity>
		<activity id="speedChange">
			<action id="setupContreTask" delay="0" repeat="0">
				<parameter name="targetObjectSpeed" value="5" />
			</action>
		</activity>
		<activity id="shutDownSim">
			<action id="shutDownSimulation" delay="0" repeat="0">
			</action>
		</activity>
		<activity id="sendText1">
			<action id="sendMessage" delay="0" repeat="4">
				<parameter name="text" value="Hello World" />
				<parameter name="duration" value="3" />
			</action>
		</activity>
		<activity id="playSound1">
			<action id="playSound" delay="0" repeat="4">
				<parameter name="soundID" value="beep" />
			</action>
		</activity>
	</activities>
	
	<triggers>
		<trigger id="TTLTriggerResume" priority="1">
			<activities>
				<activity ref="resumeSim"/>
			</activities>		
			<condition>remote:resume</condition>
		</trigger>
		<trigger id="TTLTriggerSpeedChange" priority="1">
			<activities>
				<activity ref="speedChange"/>
			</activities>		
			<condition>remote:speed</condition>
		</trigger>
		<trigger id="TTLTriggerShutDown" priority="1">
			<activities>
				<activity ref="shutDownSim"/>
			</activities>		
			<condition>remote:shutDown</condition>
		</trigger>
		<trigger id="SendTextWhenCameraAtTriggerPos1" priority="1">
			<activities>
				<activity ref="sendText1"/>
			</activities>		
			<condition>cameraWaypoint:triggerPos1</condition>
		</trigger>
		
		<trigger id="PlaySoundWhenCameraAtTriggerPos2" priority="1">
			<activities>
				<activity ref="playSound1"/>
			</activities>		
			<condition>cameraWaypoint:triggerPos2</condition>
		</trigger>
	</triggers>
	
</interaction>

=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Projects/ThreeVehiclePlatooningTask/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">


	<activities>
		<activity id="activity01">
			<action id="manipulateObject" delay="0" repeat="4">
				<parameter name="id" value="RoadworksSign1" />
				<parameter name="translationX" value="-81" />
				<parameter name="translationY" value="-1.693" />
				<parameter name="translationZ" value="-48" />
				<parameter name="rotationX" value="0" />
				<parameter name="rotationY" value="135" />
				<parameter name="rotationZ" value="0" />
				<parameter name="scaleX" value="0.02" />
				<parameter name="scaleY" value="0.02" />
				<parameter name="scaleZ" value="0.02" />
				<parameter name="visible" value="true" />
			</action>
		</activity>
		<activity id="activity02">
			<action id="sendMessage" delay="0" repeat="4">
				<parameter name="text" value="Recording started" />
				<parameter name="duration" value="3" />
			</action>
		</activity>
		<activity id="activity03">
			<action id="pauseSimulation" delay="0" repeat="4">
				<parameter name="duration" value="3" />
			</action>
		</activity>
		<activity id="activity04">
			<action id="startRecording" delay="0" repeat="4">
				<parameter name="track" value="1" />
			</action>
		</activity>
		<activity id="activity05">
			<action id="stopRecording" delay="0" repeat="4">
			</action>
		</activity>
		<activity id="activity06">
			<action id="playSound" delay="0" repeat="4">
				<parameter name="soundID" value="beep" />
			</action>
		</activity>
		<activity id="activity07">
			<action id="resetCar" delay="0" repeat="4">
				<parameter name="resetPointID" value="reset2" />
			</action>
		</activity>
		<activity id="activity08">
			<action id="moveTraffic" delay="0" repeat="4">
				<parameter name="trafficObjectID" value="car2" />
				<parameter name="wayPointID" value="205" />
			</action>
		</activity>
		<activity id="activity09">
			<action id="requestGreenTrafficLight" delay="0" repeat="0">
				<parameter name="trafficLightID" value="TrafficLight.00_00" />
			</action>
		</activity>
		<activity id="setBrakeStimulus">
			 <action id="setTVPTStimulus" delay="0" repeat="0">
                <parameter name="stimulusID" value="emergencyBrake" />
			</action>
		</activity>
		<activity id="setTurnSignalStimulus">
			 <action id="setTVPTStimulus" delay="0" repeat="0">
                <parameter name="stimulusID" value="turnSignal" />
			</action>
		</activity>
	</activities>
	
	<triggers>
		<trigger id="collideWithResetBox" priority="1">
			
			<activities>
				<activity ref="setBrakeStimulus"/>
			</activities>
						
			<condition>collideWith:BrakeTrigger1</condition>

		</trigger>
		<trigger id="collideWithResetBox" priority="1">
			
			<activities>
				<activity ref="setBrakeStimulus"/>
			</activities>
						
			<condition>collideWith:BrakeTrigger2</condition>

		</trigger>
		<trigger id="collideWithResetBox" priority="1">
			
			<activities>
				<activity ref="setBrakeStimulus"/>
			</activities>
						
			<condition>collideWith:BrakeTrigger3</condition>

		</trigger>
		<trigger id="collideWithResetBox" priority="1">
			
			<activities>
				<activity ref="setTurnSignalStimulus"/>
			</activities>
						
			<condition>collideWith:TurnSignalTrigger1</condition>

		</trigger>
		<trigger id="collideWithResetBox" priority="1">
			
			<activities>
				<activity ref="setTurnSignalStimulus"/>
			</activities>
						
			<condition>collideWith:TurnSignalTrigger2</condition>

		</trigger>
		<trigger id="collideWithResetBox" priority="1">
			
			<activities>
				<activity ref="setTurnSignalStimulus"/>
			</activities>
						
			<condition>collideWith:TurnSignalTrigger3</condition>

		</trigger>

		<trigger id="collideWithRedBox" priority="1">
			
			<activities>
				<activity ref="activity04"/>
				<activity ref="activity02"/>
				<!-- 
				<activity ref="activity08"/>
				<activity id="activity02">
					<action id="moveObject" delay="0" repeat="1">
						<parameter name="id" value="RoadWorksSign01" />
						<parameter name="translationX" value="-81" />
						<parameter name="translationY" value="-1.693" />
						<parameter name="translationZ" value="-48" />
						<parameter name="rotationX" value="90" />
						<parameter name="rotationY" value="135" />
						<parameter name="rotationZ" value="0" />
						<parameter name="scaleX" value="1" />
						<parameter name="scaleY" value="2" />
						<parameter name="scaleZ" value="2" />
						<parameter name="visible" value="true" />
						<parameter name="collidable" value="true" />
					</action>
				</activity>
				 -->
			</activities>
						
			<condition>collideWith:redBox</condition>

		</trigger>
		
		<trigger id="collideWithBlueBox" priority="1">
			
			<activities>
				<activity ref="activity05"/>
				<!-- 
				<activity ref="activity02"/>
				<activity ref="activity08"/>
				<activity id="activity02">
					<action id="moveObject" delay="0" repeat="1">
						<parameter name="id" value="RoadWorksSign01" />
						<parameter name="translationX" value="-81" />
						<parameter name="translationY" value="-1.693" />
						<parameter name="translationZ" value="-48" />
						<parameter name="rotationX" value="90" />
						<parameter name="rotationY" value="135" />
						<parameter name="rotationZ" value="0" />
						<parameter name="scaleX" value="1" />
						<parameter name="scaleY" value="2" />
						<parameter name="scaleZ" value="2" />
						<parameter name="visible" value="true" />
						<parameter name="collidable" value="true" />
					</action>
				</activity>
				 -->
			</activities>
						
			<condition>collideWith:blueBox</condition>

		</trigger>
		
		<trigger id="pressKeyB01" priority="2">
			<activities>
				<activity id="activityB01">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="201" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:1</condition>
		</trigger>
		<trigger id="pressKeyB02" priority="2">
			<activities>
				<activity id="activityB02">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="202" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:2</condition>
		</trigger>
		<trigger id="pressKeyB03" priority="2">
			<activities>
				<activity id="activityB03">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="203" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:3</condition>
		</trigger>
		<trigger id="pressKeyB04" priority="2">
			<activities>
				<activity id="activityB04">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="204" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:4</condition>
		</trigger>
		<trigger id="pressKeyB05" priority="2">
			<activities>
				<activity id="activityB05">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="205" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:5</condition>
		</trigger>
		<trigger id="pressKeyB06" priority="2">
			<activities>
				<activity id="activityB06">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="206" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:6</condition>
		</trigger>
		<trigger id="pressKeyB07" priority="2">
			<activities>
				<activity id="activityB07">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="207" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:7</condition>
		</trigger>
		<trigger id="pressKeyB08" priority="2">
			<activities>
				<activity id="activityB08">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="208" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:8</condition>
		</trigger>
		<trigger id="pressKeyB09" priority="2">
			<activities>
				<activity id="activityB09">
					<action id="moveTraffic" delay="0" repeat="4">
						<parameter name="trafficObjectID" value="car2" />
						<parameter name="wayPointID" value="209" />
					</action>
				</activity>
			</activities>	
			<condition>pressKey:9</condition>
		</trigger>
<!-- 		
		<trigger id="pressKey" priority="2">
			
			<activities>
				<activity ref="activity01"/>
				<activity ref="activity02"/>
				<activity ref="activity06"/>
			</activities>
						
			<condition>pressKey:X</condition>

		</trigger>
 -->
	</triggers>
	
</interaction>

=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Projects/ParisTraffic/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">


	<activities>
		<activity id="movePedestrianCrossing_1">
			<action id="manipulateObject" delay="0" repeat="0">
				<parameter name="id" value="PedestrianCrossing_1" />
				<parameter name="setTranslationX" value="-74.77681" />
				<parameter name="setTranslationY" value="-0.26786697" />
				<parameter name="setTranslationZ" value="5.0" />
			</action>
		</activity>
		<activity id="movePedestrianCrossing_1Back">
			<action id="manipulateObject" delay="0" repeat="0">
				<parameter name="id" value="PedestrianCrossing_1" />
				<parameter name="setTranslationX" value="-69.77681" />
				<parameter name="setTranslationY" value="-0.26786697" />
				<parameter name="setTranslationZ" value="5.0" />
			</action>
		</activity>
		<activity id="moveCar1">
			<action id="moveTraffic" delay="0" repeat="4">
				<parameter name="trafficObjectID" value="car1" />
				<parameter name="wayPointID" value="1WayPoint_6" />
			</action>
		</activity>
		<activity id="resumeSim">
			<action id="resumeSimulation" delay="0" repeat="0">
			</action>
		</activity>
	</activities>
	
	<triggers>
		<trigger id="collisionWithRedBox" priority="1">
			<activities>
				<activity ref="moveCar1"/>
			</activities>		
			<condition>collideWith:redBox</condition>
		</trigger>
		
		<trigger id="collisionWithBlueBox" priority="1">
			<activities>
				<activity ref="movePedestrianCrossing_1"/>
			</activities>		
			<condition>collideWith:blueBox</condition>
		</trigger>
		
		<trigger id="collisionWithGreenBox" priority="1">
			<activities>
				<activity ref="movePedestrianCrossing_1Back"/>
			</activities>		
			<condition>collideWith:greenBox</condition>
		</trigger>
		
		<trigger id="TTLTrigger" priority="1">
			<activities>
				<activity ref="resumeSim"/>
			</activities>		
			<condition>remote:resume</condition>
		</trigger>
	</triggers>
	
</interaction>

=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Projects/Village/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">


	<activities>
		<activity id="activity01">
			<action id="manipulateObject" delay="0" repeat="4">
				<parameter name="id" value="RoadworksSign1" />
				<parameter name="translationX" value="-81" />
				<parameter name="translationY" value="-1.693" />
				<parameter name="translationZ" value="-48" />
				<parameter name="rotationX" value="0" />
				<parameter name="rotationY" value="135" />
				<parameter name="rotationZ" value="0" />
				<parameter name="scaleX" value="0.02" />
				<parameter name="scaleY" value="0.02" />
				<parameter name="scaleZ" value="0.02" />
				<parameter name="visible" value="true" />
			</action>
		</activity>
		<activity id="activity02">
			<action id="sendMessage" delay="0" repeat="4">
				<parameter name="text" value="Rafael" />
				<parameter name="duration" value="3" />
			</action>
		</activity>
		<activity id="activity03">
			<action id="pauseSimulation" delay="0" repeat="4">
				<parameter name="duration" value="3" />
			</action>
		</activity>
		<activity id="activity04">
			<action id="startRecording" delay="0" repeat="4">
				<parameter name="track" value="1" />
			</action>
		</activity>
		<activity id="activity05">
			<action id="stopRecording" delay="0" repeat="4">
			</action>
		</activity>
		<activity id="activity06">
			<action id="playSound" delay="0" repeat="4">
				<parameter name="soundID" value="beep" />
			</action>
		</activity>
	</activities>
	
	<triggers>
		<trigger id="collideWithRedBox" priority="1">
			<activities>
				<activity ref="activity04"/>
			</activities>	
			<condition>collideWith:redBox</condition>
		</trigger>
		
		<trigger id="collideWithBlueBox" priority="1">
			<activities>
				<activity ref="activity05"/>
			</activities>		
			<condition>collideWith:blueBox</condition>
		</trigger>

	</triggers>
	
</interaction>

=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Projects/MotorwayTask/interaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<interaction xmlns="http://opends.eu/drivingtask/interaction"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/interaction ../../Schema/interaction.xsd">


	<activities>
		<activity id="startRecord">
			<action id="startRecording" delay="0" repeat="0">
				<parameter name="track" value="1" />
			</action>
		</activity>
		
		<activity id="enterMotorway">
			<action id="setMotorwayTaskStimulus" delay="0" repeat="0">
				<parameter name="stimulusID" value="enter" />
			</action>
		</activity>
		
		<activity id="exitMotorway">
			<action id="setMotorwayTaskStimulus" delay="0" repeat="0">
				<parameter name="stimulusID" value="exit" />
			</action>
		</activity>
		
		<activity id="stopRecord">
			<action id="stopRecording" delay="0" repeat="0">
			</action>
		</activity>
		
		<activity id="playMovie01">
			<action id="playMovie" delay="0" repeat="0">
				<parameter name="movieID" value="movie01" />
			</action>
		</activity>
		
		<activity id="playMovie02">
			<action id="playMovie" delay="0" repeat="0">
				<parameter name="movieID" value="movie02" />
			</action>
		</activity>
		
		<activity id="stopMovies">
			<action id="stopMovie" delay="0" repeat="0">
			</action>
		</activity>
	</activities>
	
	
	<!--TRIGGERS-->
	
	<triggers>
		<trigger id="collideWithStartRecordBox" priority="1">
            <activities>
                <activity ref="startRecord"/>
            </activities>
            
            <condition>collideWith:redBoxStartRecording</condition>
        </trigger>
        
        <trigger id="collideWithEnterMotorwayBox" priority="1">
            <activities>
                <activity ref="enterMotorway"/>
            </activities>
            
            <condition>collideWith:greenBoxEnterMotorway</condition>
        </trigger>
        
        <trigger id="collideWithExitMotorwayBox" priority="1">
            <activities>
                <activity ref="exitMotorway"/>
            </activities>
            
            <condition>collideWith:blueBoxExitMotorway</condition>
        </trigger>
        
        <trigger id="collideWithStopRecordBox" priority="1">
            <activities>
                <activity ref="stopRecord"/>
            </activities>
            
            <condition>collideWith:redBoxStopRecording</condition>
        </trigger>
        
        <trigger id="movie01play" priority="1">
            <activities>
                <activity ref="playMovie01"/>
            </activities>
            
            <condition>pressKey:5</condition>
        </trigger>
        
        <trigger id="movie02play" priority="1">
            <activities>
                <activity ref="playMovie02"/>
            </activities>
            
            <condition>pressKey:6</condition>
        </trigger>
        
        <trigger id="moviesstop" priority="1">
            <activities>
                <activity ref="stopMovies"/>
            </activities>
            
            <condition>pressKey:7</condition>
        </trigger>
		
	</triggers>
	
</interaction>
