=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Schema/task.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema targetNamespace="http://opends.eu/drivingtask/task"
elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://opends.eu/drivingtask/task">



    <xs:element name="task">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="1" minOccurs="0">
                	<xs:element name="steeringTask" type="steeringTask" maxOccurs="1" minOccurs="0">
                	</xs:element>
                	<xs:element name="threeVehiclePlatoon" type="threeVehiclePlatoon" maxOccurs="1" minOccurs="0">
                	</xs:element>
                </xs:choice>
                <xs:element name="distanceBars" type="distanceBars" maxOccurs="1" minOccurs="0">
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    
    <xs:complexType name="steeringTask">
        <xs:all>
        	<xs:element name="startPoint" type="refElement"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="endPoint" type="refElement" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="steeringTaskType" type="xs:string"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="distanceToObjects" type="xs:float"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="objectOffset" type="xs:float"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="heightOffset" type="xs:float"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="targetObject" type="steeringTaskObject"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="steeringObject" type="steeringTaskObject"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="trafficLightObject"
        		type="trafficLightObject" maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="pauseAfterTargetSet" type="xs:int"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="blinkingInterval" type="xs:int"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="database" type="database" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="additionalTable" type="xs:boolean"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        	<xs:element name="maxDeviation" type="xs:float" maxOccurs="1" minOccurs="0"></xs:element>
        	<xs:element name="conditionName" type="xs:string"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        	<xs:element name="conditionNumber" type="xs:int"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        	<xs:element name="primaryTask" type="primaryTask"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        	<xs:element name="secondaryTask" type="secondaryTask"
        		maxOccurs="1" minOccurs="1">
        	</xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="steeringTaskObject">
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="speed" type="xs:float"></xs:attribute>
        <xs:attribute name="maxLeft" type="xs:float"></xs:attribute>
        <xs:attribute name="maxRight" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="trafficLightObject">
        <xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="database">
        <xs:attribute name="url" type="xs:string"></xs:attribute>
        <xs:attribute name="user" type="xs:string"></xs:attribute>
        <xs:attribute name="password" type="xs:string"></xs:attribute>
        <xs:attribute name="table" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="primaryTask">
        <xs:all>
            <xs:element name="startPoint" type="refElement" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="endPoint" type="refElement" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="isPeripheralMode" type="xs:boolean" maxOccurs="1" minOccurs="0"></xs:element>
            <xs:element name="iconWidth" type="xs:int" maxOccurs="1" minOccurs="0"></xs:element>
            <xs:element name="iconHeight" type="xs:int" maxOccurs="1" minOccurs="0"></xs:element>
            <xs:element name="iconDistFromLeftFrameBorder" type="xs:int" maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="iconDistFromRightFrameBorder" type="xs:int" maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="lightMinPause" type="xs:int" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="lightMaxPause" type="xs:int" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="lightDuration" type="xs:int" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="blinkingThreshold" type="xs:float" maxOccurs="1" minOccurs="0"></xs:element>
            <xs:element name="minBlinkingDuration" type="xs:int" maxOccurs="1" minOccurs="0"></xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="secondaryTask">
        <xs:all>
            <xs:element name="startPoint" type="refElement" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="endPoint" type="refElement" maxOccurs="1" minOccurs="1"></xs:element>
            
            <xs:element name="waitForNextLandmark" type="xs:int" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="minTimeOfAppearance" type="xs:int" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="maxVisibilityDistance" type="xs:float" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="maxSelectionDistance" type="xs:float" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="maxAngle" type="xs:float" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="landmarkObjects" type="landmarkObjects" maxOccurs="1" minOccurs="1"></xs:element>
            <xs:element name="landmarkTextures" type="landmarkTextures" maxOccurs="1" minOccurs="1">
            </xs:element>
            <xs:element name="distractorTextures" type="distractorTextures" maxOccurs="1" minOccurs="1">
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="landmarkObjects">
        <xs:sequence>
            <xs:element name="landmarkObject" type="landmarkObject" maxOccurs="unbounded" minOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="landmarkObject">
        <xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="landmarkTextures">
        <xs:sequence>
            <xs:element name="landmarkTexture" type="landmarkTexture"
                maxOccurs="unbounded" minOccurs="1">
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="landmarkTexture">
        <xs:attribute name="url" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="distractorTextures">
        <xs:sequence>
            <xs:element name="distractorTexture" type="distractorTexture" maxOccurs="unbounded" minOccurs="1"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="distractorTexture">
        <xs:attribute name="url" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="refElement">
        <xs:attribute name="ref" type="xs:string"></xs:attribute>
    </xs:complexType>
    

    <xs:complexType name="threeVehiclePlatoon">
        <xs:all>
            <xs:element name="leadingCar" type="car" maxOccurs="1"
                minOccurs="1">
            </xs:element>
            <xs:element name="followerCar" type="car" maxOccurs="1"
                minOccurs="1">
            </xs:element>
            <xs:element name="laneOffset" type="laneOffsetType"
                maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="brakeLight" type="brakeLightType"
                maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="turnSignal" type="turnSignalType"
                maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="speedReduction" type="speedReductionType"
                maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="maxReactionTime" type="xs:int"
                maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="deviationTolerance"
                type="deviationToleranceType" maxOccurs="1"
                minOccurs="0">
            </xs:element>
            <xs:element name="distanceIndicator" type="distanceTextType" maxOccurs="1" minOccurs="0"></xs:element>
            <xs:element name="logging" type="loggingType" maxOccurs="1"
                minOccurs="0">
            </xs:element>

        </xs:all>

    </xs:complexType>

    <xs:complexType name="car">
        <xs:attribute name="id" type="xs:string"></xs:attribute>
        <xs:attribute name="minDistance" type="xs:float"></xs:attribute>
        <xs:attribute name="maxDistance" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="brakeLightType">
        <xs:attribute name="minDuration" type="xs:int"></xs:attribute>
        <xs:attribute name="resetOnReaction" type="xs:boolean"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="turnSignalType">
        <xs:attribute name="duration" type="xs:int"></xs:attribute>
        <xs:attribute name="resetOnReaction" type="xs:boolean"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="deviationToleranceType">
        <xs:all>
            <xs:element name="longitudinal" type="deviationType" maxOccurs="1" minOccurs="0"></xs:element>
            <xs:element name="lateral" type="deviationType"
                maxOccurs="1" minOccurs="0">
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="deviationType">
        <xs:attribute name="lowerBound" type="xs:float"></xs:attribute>
        <xs:attribute name="upperBound" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="laneOffsetType">
        <xs:attribute name="x" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="loggingType">
        <xs:all>
            <xs:element name="startPosition" type="startPositionType"
                maxOccurs="1" minOccurs="1">
            </xs:element>
            <xs:element name="endPosition" type="endPositionType"
                maxOccurs="1" minOccurs="1">
            </xs:element>
            <xs:element name="loggingRate" type="xs:float" maxOccurs="1"
                minOccurs="0">
            </xs:element>
            <xs:element name="database" type="databaseType"
                maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="condition" type="conditionType"
                maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="reportTemplate" type="xs:string"
                maxOccurs="1" minOccurs="0">
            </xs:element>
            <xs:element name="additionalTable" type="xs:boolean" maxOccurs="1" minOccurs="0"></xs:element>
        </xs:all>

    </xs:complexType>

    <xs:complexType name="startPositionType">
    	<xs:attribute name="z" type="xs:float"></xs:attribute>
    	<xs:attribute name="shutDownAfterXSeconds" type="xs:int"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="endPositionType">
        <xs:attribute name="z" type="xs:float"></xs:attribute>
        <xs:attribute name="shutDownWhenReached" type="xs:boolean"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="databaseType">
        <xs:attribute name="url" type="xs:string"></xs:attribute>
        <xs:attribute name="user" type="xs:string"></xs:attribute>
        <xs:attribute name="password" type="xs:string"></xs:attribute>
        <xs:attribute name="table" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="conditionType">
        <xs:attribute name="name" type="xs:string"></xs:attribute>
        <xs:attribute name="number" type="xs:int"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="speedReductionType">
    	<xs:attribute name="targetSpeedMinRegular" type="xs:float"></xs:attribute>
    	<xs:attribute name="targetSpeedMaxRegular" type="xs:float"></xs:attribute>
    	<xs:attribute name="targetSpeedMinEmergency" type="xs:float"></xs:attribute>
    	<xs:attribute name="targetSpeedMaxEmergency" type="xs:float"></xs:attribute>
    	<xs:attribute name="minSpeed" type="xs:float"></xs:attribute>
    	<xs:attribute name="duration" type="xs:int"></xs:attribute>
    	<xs:attribute name="minTimeAllConditionsMet" type="xs:int"></xs:attribute>
    	<xs:attribute name="resetOnReaction" type="xs:boolean"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="distanceTextType">
        <xs:all>
        	<xs:element name="hideAtPosition" type="hideAtPositionType"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        	<xs:element name="showText" type="positionType"
        		maxOccurs="1" minOccurs="0">
        	</xs:element>
        	<xs:element name="showLongitudinalDistanceBar"
        		type="showLongitudinalDistanceBar" maxOccurs="1"
        		minOccurs="0">
        	</xs:element>
        	<xs:element name="showLateralDeviationBar" type="showLateralDeviationBar" maxOccurs="1" minOccurs="0"></xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="hideAtPositionType">
        <xs:attribute name="z" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="positionType">
    	<xs:attribute name="top" type="xs:int"></xs:attribute>
    	<xs:attribute name="bottom" type="xs:int"></xs:attribute>
    	<xs:attribute name="left" type="xs:int"></xs:attribute>
    	<xs:attribute name="right" type="xs:int"></xs:attribute>
    	<xs:attribute name="scale" type="xs:float"></xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="distanceBars">
    	<xs:sequence>
            <xs:element name="distanceBar" type="distanceBar"
            	maxOccurs="unbounded" minOccurs="0">
            </xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="distanceBar">
        <xs:all>
        	<xs:element name="width" type="xs:float" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="height" type="xs:float" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="left" type="xs:float" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="bottom" type="xs:float" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="rotation" type="xs:float" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="showText" type="xs:boolean" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        	<xs:element name="segments" type="segments" maxOccurs="1"
        		minOccurs="1">
        	</xs:element>
        </xs:all>

        <xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="segments">
    	<xs:sequence>
    		<xs:element name="segment" type="segment"
    			maxOccurs="unbounded" minOccurs="1">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="segment">
    	<xs:attribute name="name" type="xs:string"></xs:attribute>
    	<xs:attribute name="type">
    		<xs:simpleType>
    			<xs:restriction base="xs:string">
    				<xs:enumeration value="red"></xs:enumeration>
    				<xs:enumeration value="green"></xs:enumeration>
    				<xs:enumeration value="redToGreen"></xs:enumeration>
    				<xs:enumeration value="greenToRed"></xs:enumeration>
    			</xs:restriction>
    		</xs:simpleType>
    	</xs:attribute>
    	<xs:attribute name="minValue" type="xs:float"></xs:attribute>
    	<xs:attribute name="maxValue" type="xs:float"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="showLongitudinalDistanceBar">
    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="showLateralDeviationBar">
    	<xs:attribute name="id" type="xs:string"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Projects/ConTReTask/task.xml
<?xml version="1.0" encoding="UTF-8"?>
<task xmlns="http://opends.eu/drivingtask/task"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/task ../../Schema/task.xsd">
        
    <steeringTask>
		<startPoint ref="startPointPrimaryTask" />
		<endPoint ref="endTasks" />
		<steeringTaskType>driver</steeringTaskType>
		<distanceToObjects>30</distanceToObjects>
		<objectOffset>-0.1</objectOffset>
		<heightOffset>2.5</heightOffset>
		<targetObject id="yellowCylinder" speed="0.5" maxLeft="6" maxRight="2" />
		<steeringObject id="blueCylinder" speed="4" maxLeft="6" maxRight="2" />
		<trafficLightObject id="trafficLightBox" />
		<pauseAfterTargetSet>2000</pauseAfterTargetSet>
		<blinkingInterval>150</blinkingInterval>
		<database url="jdbc:mysql:///simulator" user="root" password="" table="car_experiment_results" />
		<additionalTable>true</additionalTable>
		<conditionName>speech</conditionName>
		<conditionNumber>123</conditionNumber>

		<primaryTask>
			<startPoint ref="startPointPrimaryTask" />
			<endPoint ref="endTasks" />
			<isPeripheralMode>false</isPeripheralMode>
			<iconWidth>73</iconWidth>
			<iconHeight>73</iconHeight>
			<iconDistFromLeftFrameBorder>100</iconDistFromLeftFrameBorder>
			<iconDistFromRightFrameBorder>100</iconDistFromRightFrameBorder>
			<lightMinPause>10000</lightMinPause>
			<lightMaxPause>15000</lightMaxPause>
			<lightDuration>5000</lightDuration>
			<blinkingThreshold>1.0</blinkingThreshold>
			<minBlinkingDuration>1000</minBlinkingDuration>
		</primaryTask>
		
		<secondaryTask>
			<startPoint ref="startPointSecondaryTask" />
			<endPoint ref="endTasks" />
			<waitForNextLandmark>3000</waitForNextLandmark>
			<minTimeOfAppearance>2000</minTimeOfAppearance>
			<maxVisibilityDistance>500</maxVisibilityDistance>
			<maxSelectionDistance>200</maxSelectionDistance>
			<maxAngle>45</maxAngle>
			<landmarkObjects>
				<landmarkObject id="house01"/>
				<landmarkObject id="house02"/>
				<landmarkObject id="house03"/>
				<landmarkObject id="house04"/>
				<landmarkObject id="house05"/>
				<landmarkObject id="house06"/>
				<landmarkObject id="house07"/>
				<landmarkObject id="house08"/>
				<landmarkObject id="house09"/>
				<landmarkObject id="house10"/>
				<landmarkObject id="house11"/>
				<landmarkObject id="house12"/>
				<landmarkObject id="house13"/>
				<landmarkObject id="house14"/>
				<landmarkObject id="house15"/>
				<landmarkObject id="house16"/>
				<landmarkObject id="house17"/>
				<landmarkObject id="house18"/>
				<landmarkObject id="house19"/>
				<landmarkObject id="house20"/>
				<landmarkObject id="house21"/>
				<landmarkObject id="house22"/>
				<landmarkObject id="house23"/>
				<landmarkObject id="house24"/>
			</landmarkObjects>
			<landmarkTextures>
				<landmarkTexture url="Textures/ReactionTest/landmarks/akropolis.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/atomium.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/brandenburgerTor.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/cheopsPyramide.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/eiffelturm.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/freiheitsstatue.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/goldenGateBridge.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/petersdom.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/sacreCoeur.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/tajMahal.jpg" />
				<landmarkTexture url="Textures/ReactionTest/landmarks/towerBridge.jpg" />
			</landmarkTextures>
			<distractorTextures>
				<distractorTexture url="Textures/ReactionTest/buildings/build01.jpg"/>
				<distractorTexture url="Textures/ReactionTest/buildings/build02.jpg"/>
				<distractorTexture url="Textures/ReactionTest/buildings/build03.jpg"/>
				<distractorTexture url="Textures/ReactionTest/buildings/build04.jpg"/>
				<distractorTexture url="Textures/ReactionTest/buildings/build05.jpg"/>
				<distractorTexture url="Textures/ReactionTest/buildings/build06.jpg"/>
				<distractorTexture url="Textures/ReactionTest/buildings/build07.jpg"/>
			</distractorTextures>
		</secondaryTask>
	</steeringTask>
</task>

=== FlorianPusse/OpenDS-CTS/assets/DrivingTasks/Projects/ThreeVehiclePlatooningTask/task.xml
<?xml version="1.0" encoding="UTF-8"?>
<task xmlns="http://opends.eu/drivingtask/task"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
        xsi:schemaLocation="http://opends.eu/drivingtask/task ../../Schema/task.xsd">
        
    <threeVehiclePlatoon>
        <leadingCar id="car1" minDistance="20" maxDistance="50" />
        <followerCar id="car2" minDistance="5" maxDistance="15" />
        <laneOffset x="2.204541" />
        <brakeLight minDuration="2500" resetOnReaction="true" />
        <turnSignal duration="2500" resetOnReaction="true" />
        <speedReduction targetSpeedMinRegular="50" targetSpeedMaxRegular="50" targetSpeedMinEmergency="0" 
                targetSpeedMaxEmergency="0" minSpeed="20" duration="5000" minTimeAllConditionsMet="1000" 
                resetOnReaction="false" />
        <maxReactionTime>5000</maxReactionTime>
        <deviationTolerance>
            <longitudinal lowerBound="20" upperBound="35" />
            <lateral lowerBound="-2" upperBound="3"/>
        </deviationTolerance>
        <distanceIndicator>
            <hideAtPosition z="6750" />
            <!-- <showText top="300" left="409" scale="3" /> -->
            <showLongitudinalDistanceBar id="verticalBar" />
            <showLateralDeviationBar id="horizontalBar" />
        </distanceIndicator> 
        <logging>
            <startPosition z="6800" />
            <endPosition z="5000" shutDownWhenReached="false"/>
            <loggingRate>20</loggingRate>
            <database url="jdbc:mysql:///simulator" user="root" password="" table="tvpt" />   
            <condition name="baseline" number="1" />
            <reportTemplate>assets/JasperReports/templates/tvpt.jasper</reportTemplate>
            <additionalTable>true</additionalTable>
        </logging>
    </threeVehiclePlatoon>
    <distanceBars>
	    <distanceBar id="verticalBar">
	    	<width>20</width>
	    	<height>200</height>
	    	<left>700</left>
	    	<bottom>300</bottom>
	    	<rotation>180</rotation>
	    	<showText>true</showText>
	    	<segments>
	    		<segment name="0" type="red" minValue="0" maxValue="15" />
	    		<segment name="1" type="redToGreen" minValue="15" maxValue="25" />
	    		<segment name="2" type="green" minValue="25" maxValue="30" />
	    		<segment name="3" type="greenToRed" minValue="30" maxValue="40" />
	    		<segment name="4" type="red" minValue="40" maxValue="55" />
	    	</segments>				
	    </distanceBar>
	    <distanceBar id="horizontalBar">
	    	<width>20</width>
	    	<height>200</height>
	    	<left>800</left>
	    	<bottom>50</bottom>
	    	<rotation>270</rotation>
	    	<showText>true</showText>
	    	<segments>
	    		<segment name="0" type="red" minValue="-5" maxValue="-2" />
	    		<segment name="1" type="redToGreen" minValue="-2" maxValue="0" />
	    		<segment name="2" type="greenToRed" minValue="0" maxValue="2" />
	    		<segment name="3" type="red" minValue="2" maxValue="5" />
	    	</segments>
	    </distanceBar>
    </distanceBars>
</task>
